export enum ArticleCategory {
  RESEARCH_TOOLS = 'RESEARCH_TOOLS',
  APPLICATION_DEVELOPMENT = 'APPLICATION_DEVELOPMENT',
  TEAM_UPDATES = 'TEAM_UPDATES',
  COMPANY_NEWS = 'COMPANY_NEWS',
  FUTURE_PLANS = 'FUTURE_PLANS',
  INNOVATION = 'INNOVATION',
  AWARDS = 'AWARDS',
  INNOVATIONS = 'INNOVATIONS',
  COLLABORATION = 'COLLABORATION',
  PRODUCT_UPDATES = 'PRODUCT_UPDATES',
  GLOBAL_EXPANSION = 'GLOBAL_EXPANSION',
  DATA_ANALYSIS = 'DATA_ANALYSIS',
  RESEARCH_PARTNERSHIPS = 'RESEARCH_PARTNERSHIPS',
  USER_EXPERIENCE = 'USER_EXPERIENCE',
  APPLICATION_DESIGN = 'APPLICATION_DESIGN'
}
