export enum SkeletonType {
  FORM_FIELD = 'FORM_FIELD',
  FORM_FIELD_WITHOUT_LABEL = 'FORM_FIELD_WITHOUT_LABEL',
  BUTTON = 'BUTTON',
  IMAGE = 'IMAGE',
  ARTICLE_IMAGE = 'ARTICLE_IMAGE',
  ARTICLE_AUTHOR_IMAGE = 'ARTICLE_AUTHOR_IMAGE',
  ARTICLE_AUTHOR_NAME = 'ARTICLE_AUTHOR_NAME',
  DISPLAY_LG = 'DISPLAY_LG',
  DISPLAY_MD = 'DISPLAY_MD',
  DISPLAY_SM = 'DISPLAY_SM',
  DISPLAY_XS = 'DISPLAY_XS',
  TEXT_XL = 'TEXT_XL',
  TEXT_MD = 'TEXT_MD',
  TEXT_SM = 'TEXT_SM',
  PARAGRAPH_LG = 'PARAGRAPH_LG',
  BADGE_SM = 'BADGE_SM',
  BADGE_MD = 'BADGE_MD',
  BADGE_LG = 'BADGE_LG',
  TABLE_AVATAR = 'TABLE_AVATAR'
  // MAIN_ARTICLE = 'MAIN_ARTICLE',
  // ARTICLE = 'ARTICLE'
}
