export enum SkeletonType {
  FORM_FIELD = 'FORM_FIELD',
  BUTTON = 'BUTTON',
  IMAGE = 'IMAGE',
  ARTICLE_IMAGE = 'ARTICLE_IMAGE',
  ARTICLE_AUTHOR_IMAGE = 'ARTICLE_AUTHOR_IMAGE',
  ARTICLE_AUTHOR_NAME = 'ARTICLE_AUTHOR_NAME',
  DISPLAY_MD = 'DISPLAY_MD',
  DISPLAY_XS = 'DISPLAY_XS',
  TEXT_MD = 'TEXT_MD',
  TEXT_SM = 'TEXT_SM'
  // MAIN_ARTICLE = 'MAIN_ARTICLE',
  // ARTICLE = 'ARTICLE'
}
