export enum SkeletonType {
  FORM_FIELD = 'FORM_FIELD',
  BUTTON = 'BUTTON',
  IMAGE = 'IMAGE',
  CHIP = 'CHIP',
  ARTICLE_IMAGE = 'ARTICLE_IMAGE',
  ARTICLE_AUTHOR_IMAGE = 'ARTICLE_AUTHOR_IMAGE',
  ARTICLE_AUTHOR_NAME = 'ARTICLE_AUTHOR_NAME',
  DISPLAY_LG = 'DISPLAY_LG',
  DISPLAY_MD = 'DISPLAY_MD',
  DISPLAY_SM = 'DISPLAY_SM',
  DISPLAY_XS = 'DISPLAY_XS',
  TEXT_XL = 'TEXT_XL',
  TEXT_MD = 'TEXT_MD',
  TEXT_SM = 'TEXT_SM',
  PARAGRAPH_LG = 'PARAGRAPH_LG'
  // MAIN_ARTICLE = 'MAIN_ARTICLE',
  // ARTICLE = 'ARTICLE'
}
