export enum ResearchDeviceType {
  MICROSCOPE = 'MICROSCOPE',
  SPECTROMETER = 'SPECTROMETER',
  PARTICLE_ACCELERATOR = 'PARTICLE_ACCELERATOR',
  TELESCOPE = 'TELESCOPE',
  XRAY_DIFFRACTION_MACHINE = 'XRAY_DIFFRACTION_MACHINE',
  DNA_SEQUENCER = 'DNA_SEQUENCER',
  CHROMATOGRAPH = 'CHROMATOGRAPH',
  CLIMATE_SIMULATOR = 'CLIMATE_SIMULATOR',
  GEIGER_COUNTER = 'GEIGER_COUNTER',
  SQUID = 'SQUID',
  FUSION_REACTOR = 'FUSION_REACTOR',
  NEUTRON_GENERATOR = 'NEUTRON_GENERATOR',
  CRYOSTAT = 'CRYOSTAT',
  EEG_MACHINE = 'EEG_MACHINE',
  FLUOROMETER = 'FLUOROMETER',
  SEISMOMETER = 'SEISMOMETER'
}
