export enum BusinessProgram {
  BUSINESS_ECONOMICS = 'BUSINESS_ECONOMICS',
  BUSINESS_ENGINEERING = 'BUSINESS_ENGINEERING',
  BUSINESS_AND_INFORMATION_SYSTEMS_ENGINEERING = 'BUSINESS_AND_INFORMATION_SYSTEMS_ENGINEERING',
  BUSINESS_ADMINISTRATION = 'BUSINESS_ADMINISTRATION',
  MANAGEMENT = 'MANAGEMENT'
}
