export enum Faculty {
  ARCHITECTURE_AND_ARTS = 'ARCHITECTURE_AND_ARTS',
  BUSINESS_ECONOMICS = 'BUSINESS_ECONOMICS',
  MEDICINE_AND_LIFE_SCIENCES = 'MEDICINE_AND_LIFE_SCIENCES',
  ENGINEERING_TECHNOLOGY = 'ENGINEERING_TECHNOLOGY',
  TRANSPORTATION_SCIENCES = 'TRANSPORTATION_SCIENCES',
  LAW = 'LAW',
  REHABILITATION_SCIENCES = 'REHABILITATION_SCIENCES',
  SOCIAL_SCIENCES = 'SOCIAL_SCIENCES',
  SCIENCES = 'SCIENCES',
  EDUCATIONAL_STUDIES = 'EDUCATIONAL_STUDIES'
}
