export enum MedicineAndLifeProgram {
  MEDICINE = 'MEDICINE',
  BIOMEDICAL_SCIENCES = 'BIOMEDICAL_SCIENCES',
  NURSING_AND_MIDWIFERY = 'NURSING_AND_MIDWIFERY',
  HEALTH_CARE_ENGINEERING = 'HEALTH_CARE_ENGINEERING'
}
