export enum SciencesProgram {
  BIOLOGY = 'BIOLOGY',
  CHEMISTRY = 'CHEMISTRY',
  PHYSICS = 'PHYSICS',
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  MATHEMATICS = 'MATHEMATICS',
  STATISTICS_AND_DATA_SCIENCE = 'STATISTICS_AND_DATA_SCIENCE',
  MATERIOMICS = 'MATERIOMICS'
}
