export enum TableDataType {
  TEXT = 'TEXT',
  TEXT_AND_DESCRIPTION = 'TEXT_AND_DESCRIPTION',
  BADGE = 'BADGE',
  MULTIPLE_BADGES = 'MULTIPLE_BADGES',
  AVATAR = 'AVATAR',
  DATE = 'DATE',
  DELETE = 'DELETE',
  EDIT = 'EDIT'
}
