export enum ChangePasswordResponse {
  PASSWORD_EMPTY = 'PASSWORD_EMPTY',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_IDENTICAL = 'PASSWORD_IDENTICAL',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED'
}
